# Generated by Django 3.2.7 on 2022-03-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_APP', '0002_groundnut_disease_potato_disease_pulses_disease_rice_disease_tomato_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundnut_disease',
            name='desc',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='potato_disease',
            name='desc',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='pulses_disease',
            name='desc',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='rice_disease',
            name='desc',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tomato_disease',
            name='desc',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='wheat_disease',
            name='desc',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
