# Generated by Django 3.2.7 on 2022-03-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_APP', '0003_auto_20220315_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundnut_disease',
            name='rem',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='potato_disease',
            name='rem',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pulses_disease',
            name='rem',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='rice_disease',
            name='rem',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tomato_disease',
            name='rem',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='wheat_disease',
            name='rem',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
